import '../../api/messages/messages.coffee'

import '../server/mailer'
import '../server/prerenderio'

import '../common/moment'
import '../common/rolesExtensions'

import '../../api/dashboard/service'
import '../../api/dashboard/myProjects/service'
import '../../api/dashboard/missingShiftReports/service'
import '../../api/dashboard/upcomingShifts/service'
import '../../api/dashboard/pendingRequests/service'
import '../../api/dashboard/olderShifts/service'
import '../../api/languages/service'
import '../../api/projects/service'
import '../../api/shifts/service'
import '../../api/users/service'
import '../../api/users/online/service'
import '../../api/publishers/service'
import '../../api/vessels/service'
import '../../api/notes/service'
import '../../api/calendar/service'
