export enum DomainError {
  TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',
  PUBLISHER_NOT_FOUND = 'PUBLISHER_NOT_FOUND',
  TEAM_ALREADY_FULL = 'TEAM_ALREADY_FULL',
  TEAM_HAS_EXPIRED = 'TEAM_HAS_EXPIRED'
}

export enum OperationError {
  CANNOT_BE_NULL = 'CANNOT_BE_NULL'
}